@startuml activity-chronosdiff-ja
start
:Webサイトを立ち上げる\nhttp://demoaut-mimic.kazurayam.com/;
:このサイトのページを複数開いて\nスナップショットを取得する;
:時間を空けて;
:同じWebサイトを立ち上げる\nhttp://demoaut-mimic.kazurayam.com/;
:このサイトのページを複数開いて\nスナップショットを取得する;
:二つのスナップショット（別のタイミングで\n撮ったもの、同じURLどおし）を比較する;
:レポートを生成する;
stop
@enduml
