@startuml chronos-diff
actor Tester as tester
box "My PC"
participant "Test Cases/\nCURA/main" as main
participant "Test Cases/\nCURA/materialize" as materialize
note left of materialize #Yellow : Tester have to develop the\nTest Case "materialize"
database store
entity Report as report
endbox
database "store-backup" as storebk
box "External\nnetwork" #LightBlue
entity "web site" as site
endbox

== 1st run ==
tester -> main : run main
main -> storebk : restore the previous result
storebk -> store
main -> materialize : call materialize
loop : for N pages
materialize -> site : GET http://demoaut-mimic.kazurayam.com/XXXX
materialize <-- site
materialize -> materialize : take screenshot
materialize -> materialize : save HTML source
materialize -> store : write file
end
main <-- materialize
main -> main : diff current & previous
main -> report : make HTML report
main -> store : backup the current result
store -> storebk
tester <-- main

== 2nd run ==
... later after some seconds/minutes/hours/days ...
tester -> main : run main
main -> storebk : restore the previous result
storebk -> store
main -> materialize : call materialize
loop : for N pages
materialize -> site : GET http://demoaut-mimic.kazurayam.com/XXXX
materialize <-- site
materialize -> materialize : take screenshot
materialize -> materialize : save HTML source
materialize -> store : write file
end
main <-- materialize
main -> main : diff current & previous
main -> report : make HTML report
main -> store : backup the current result
store -> storebk
tester <-- main


== more runs ==
... later after some seconds/minutes/hours/days ...
tester -> main :run
note over main: do the same above

@enduml
